### ISSUE TITLE
Unifi AP fails to adapt as Bridge Device

### ISSUE THREAD

**Issue by xorinzor** [dciancu/unifi-protect-unvr-docker-arm64#12]
When I click `Add Link` on the AP to add it as bridge device, the AP status goes to `offline`, and after a second or two comes back as `online` without having been added.

![screenshot](https://github.com/user-attachments/assets/077c3eaa-c7e7-438f-8d88-36b876bad6cf)

The `/srv/unifi-protect/logs/devices.bridges.log` shows this error:
```
2024-08-29T16:02:25.581Z - info: websocket connected U6-Lite [MAC_HIDDEN @ IP_HIDDEN]
2024-08-29T16:02:25.587Z - info: Got info from U6-Lite [MAC_HIDDEN @ IP_HIDDEN] {"caps":{"addrTypes":["public"],"connDuplicateMac":false,"connParmsChange":true,"connPhyChange":true,"connPhys":["1M","coded"],"discPhys":["1M","coded"]},"id":"fac19580-4d53-332d-c9ea-3145fd363c54","runtime":2571,"type":"BLE-Bridge","version":"2.2.0"}
2024-08-29T16:02:25.608Z - error: bridge v2 connection establish failed Invalid payload: Client ID is missing
Error: Invalid payload: Client ID is missing
    at e.exports.onMessage (/usr/share/unifi-protect/app/webpack:/unifi-protect/src/middleware/devices/websockets/Connection.js:181:53)
    at Streamer.<anonymous> (/usr/share/unifi-protect/app/webpack:/unifi-protect/src/middleware/devices/websockets/Connection.js:57:12)
    at Streamer.emit (/usr/share/unifi-protect/app/node_modules/eventemitter3/index.js:181:35)
    at s.callback (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:110:39)
    at s.onUnpack (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Message.js:50:8)
    at done (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Message.js:25:10)
    at cb (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:24:18)
    at val (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:15:29)
    at s.parser (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:15:38)
    at s.write (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Partial.js:44:10)
    at s.write (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Partial.js:40:17)
    at s.feed (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Message.js:44:27)
    at s.feed (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/lib/Message.js:43:53)
    at Streamer.feed (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:124:27)
    at Streamer.newMessage (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:119:20)
    at Streamer.feed (/usr/share/unifi-protect/app/webpack:/unifi-protect/node_modules/@ubnt/binme/index.js:126:12)
2024-08-29T16:03:25.612Z - info: disconnect peers associated with U6-Lite [MAC_HIDDEN @ IP_HIDDEN]
```

This also happens when I configure protect to Auto-Adapt the bridge devices.
I have been unable to find any similar issues on google relating to this error message.

**Comment by xorinzor** [comment]
This does not seem to impact any functionality for Protect, so I'll just close this.

**Comment by dciancu** [comment]
Sorry but I did not manage to find the time to look into this.
All the best and a happy new year!
